import { describe, expect, it } from "vitest";
import * as XLSX from "xlsx";
import { EXPECTED_SHEETS, SHEET_SPECS, extractRows, findHeaderRow, normalizeHeader } from "./import-parsing";
import { SAMPLE_WORKBOOK_FILENAME, buildSampleWorkbook } from "./import-template";

/**
 * The template is only worth offering if the importer accepts it, so these tests read the
 * generated bytes back through the PARSER rather than through any knowledge of how they
 * were written. That closes the failure this design exists to prevent: the application
 * handing a QA Lead a file the application then rejects.
 *
 * The sheets are read the same way `runWorkbookImport` reads them —
 * `sheet_to_json(..., { header: 1 })` — so a change to `SHEET_SPECS` that the template
 * does not follow fails here, not in production.
 */

const workbook = XLSX.read(buildSampleWorkbook(), { type: "buffer", cellDates: true });
const gridFor = (sheet: string) =>
  XLSX.utils.sheet_to_json<unknown[]>(workbook.Sheets[sheet], {
    header: 1,
    defval: null,
    blankrows: true
  });

const SPECS = Object.values(SHEET_SPECS);
/** The two that ship deliberately empty — see `import-template.ts`. */
const HEADER_ONLY = ["Test Execution", "Execution History"];

describe("sample workbook", () => {
  it("is a real xlsx with a stable download name", () => {
    expect(SAMPLE_WORKBOOK_FILENAME).toBe("qams-import-template.xlsx");
    expect(buildSampleWorkbook().byteLength).toBeGreaterThan(0);
  });

  it("contains every sheet the importer demands, in source order", () => {
    // Not just the parsed ones: `createImportRun` refuses a workbook missing ANY of
    // EXPECTED_SHEETS, Home and Dashboard included, before it reads a single row.
    expect(workbook.SheetNames).toEqual([...EXPECTED_SHEETS]);
  });

  it("carries the two unparsed sheets as guidance, not as data", () => {
    for (const sheet of ["Home", "Dashboard"]) {
      expect(workbook.SheetNames).toContain(sheet);
      const text = gridFor(sheet).flat().map(normalizeHeader).join(" ");
      expect(text).toMatch(/not imported/i);
    }
  });

  it.each(SPECS.map((spec) => [spec.sheet, spec] as const))(
    "%s: the parser finds its header row",
    (_sheet, spec) => {
      const header = findHeaderRow(gridFor(spec.sheet), spec);
      // Not null is the whole point: null here is the importer refusing the file.
      expect(header).not.toBeNull();
      expect(header?.headerRowIndex).toBe(0);
      // No stray columns to report and ignore.
      expect(header?.unknownColumns).toEqual([]);
    }
  );

  it.each(SPECS.map((spec) => [spec.sheet, spec] as const))(
    "%s: headers appear once, in spec order",
    (_sheet, spec) => {
      const headerRow = (gridFor(spec.sheet)[0] ?? []).map(normalizeHeader);
      expect(headerRow).toEqual([...spec.requiredHeaders]);
    }
  );

  it.each(
    SPECS.filter((spec) => !HEADER_ONLY.includes(spec.sheet)).map((spec) => [spec.sheet, spec] as const)
  )("%s: every example row is COMPLETE, never PARTIAL", (_sheet, spec) => {
    const rows = gridFor(spec.sheet);
    const header = findHeaderRow(rows, spec);
    const extracted = extractRows(rows, header!, spec);

    expect(extracted.length).toBeGreaterThan(0);
    // PARTIAL is what the importer reports as ROW_INCOMPLETE — a template that shipped
    // one would tell the reader that a half-filled row is acceptable.
    expect(extracted.filter((row) => row.kind !== "COMPLETE")).toEqual([]);
  });

  it.each(HEADER_ONLY)("%s: ships headers with no example rows", (sheet) => {
    const spec = SPECS.find((s) => s.sheet === sheet)!;
    const rows = gridFor(sheet);
    const header = findHeaderRow(rows, spec);

    expect(header).not.toBeNull();
    // Deliberate: the Tester column must name a user that exists in the destination,
    // so any invented value would be rejected on upload.
    expect(extractRows(rows, header!, spec).filter((r) => r.kind !== "BLANK")).toEqual([]);
  });

  it("chains its example IDs through the hierarchy", () => {
    const cell = (sheet: string, row: number, column: number) =>
      normalizeHeader(gridFor(sheet)[row]?.[column]);

    expect(cell("Product Master", 1, 0)).toBe("PROD001");
    // Module -> Product, Feature -> Module, Requirement -> Feature.
    expect(cell("Module Master", 1, 1)).toBe("PROD001");
    expect(cell("Feature Master", 1, 1)).toBe("MOD001");
    expect(cell("Requirement Master", 1, 1)).toBe("FEAT001");

    // The test case names all four ancestors, and steps/defect/RTM name the case.
    const testCase = gridFor("Test Repository")[1]!.slice(0, 5).map(normalizeHeader);
    expect(testCase).toEqual(["TC-PROD001-0001", "PROD001", "MOD001", "FEAT001", "REQ001"]);
    expect(cell("Test Steps", 1, 0)).toBe("TC-PROD001-0001");
    expect(cell("Bug Tracker", 1, 1)).toBe("TC-PROD001-0001");
    expect(cell("RTM", 1, 1)).toBe("TC-PROD001-0001");
    expect(cell("RTM", 1, 2)).toBe("BUG-0001");
  });

  it("numbers its steps from 1 with no gap", () => {
    const rows = gridFor("Test Steps").slice(1).filter((row) => normalizeHeader(row[0]) !== "");
    expect(rows.map((row) => Number(row[1]))).toEqual([1, 2, 3]);
  });

  it("only uses controlled values it also seeds on the Settings sheet", () => {
    const settings = gridFor("Settings").slice(1);
    const column = (index: number) =>
      settings.map((row) => normalizeHeader(row[index])).filter((value) => value !== "");

    const [priorities, severities] = [column(0), column(1)];
    const testCaseRow = gridFor("Test Repository")[1]!.map(normalizeHeader);

    // Priority and Severity sit at indexes 9 and 10 of the Test Repository header set.
    expect(priorities).toContain(testCaseRow[9]);
    expect(severities).toContain(testCaseRow[10]);
  });
});
